import Foundation

/// The `transcript.json` that sits beside `audio.m4a` in a note directory.
///
/// Word-level timings are the point of this file, not a detail of it: §9
/// requires every AI-generated line to link back to the second of audio it came
/// from, and a summary can only carry a timestamp range if the words underneath
/// it have timestamps. Storing only the flat text would make that impossible to
/// add later without re-transcribing everything.
///
/// Field names are spelled out rather than abbreviated. This is a derived file,
/// but it is a derived file people will open when something looks wrong, and
/// `{"w":"the","s":0.08}` is a puzzle where `{"word":"the","start":0.08}` is a
/// sentence.
public struct Transcript: Codable, Equatable, Sendable {
    public struct Word: Codable, Equatable, Sendable {
        public let word: String
        public let start: Double
        public let end: Double

        public init(word: String, start: Double, end: Double) {
            self.word = word
            self.start = start
            self.end = end
        }
    }

    /// Bumped when the shape changes incompatibly, so a reader can tell an old
    /// transcript from a corrupt one.
    public var version: Int
    /// Which engine produced this, because a note transcribed by a cloud model
    /// has to be labelled as such (§6) and that starts with recording it here.
    public var engine: String
    public var language: String?
    public var durationSeconds: Double
    public var text: String
    public var words: [Word]

    public init(
        version: Int = 1, engine: String, language: String? = nil, durationSeconds: Double,
        text: String, words: [Word]
    ) {
        self.version = version
        self.engine = engine
        self.language = language
        self.durationSeconds = durationSeconds
        self.text = text
        self.words = words
    }

    public func write(to url: URL) throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        try encoder.encode(self).write(to: url, options: .atomic)
    }

    public static func read(from url: URL) throws -> Transcript {
        try JSONDecoder().decode(Transcript.self, from: Data(contentsOf: url))
    }
}

/// Rewrites a committed note once its words are known.
public enum NoteUpdater {
    /// A title drawn from what was actually said.
    ///
    /// The first few words, cut at a sentence boundary when there is one close
    /// enough. Deliberately not a summary: a title generated by a model is a
    /// second thing that can be wrong, and the opening words of a thought are
    /// usually what the person would have typed anyway.
    public static func title(from text: String, fallback: String) -> String {
        let cleaned = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleaned.isEmpty else { return fallback }

        // Prefer a natural stop inside the first ~60 characters.
        let head = String(cleaned.prefix(80))
        if let stop = head.firstIndex(where: { ".!?".contains($0) }) {
            let sentence = String(head[head.startIndex..<stop])
                .trimmingCharacters(in: .whitespaces)
            if sentence.count >= 12 { return sentence }
        }

        let words = cleaned.split(separator: " ").prefix(9)
        var candidate = words.joined(separator: " ")
        // Drop a trailing comma or similar so the title doesn't end mid-breath.
        while let last = candidate.last, ",;:-".contains(last) {
            candidate.removeLast()
        }
        if candidate.count > 72 {
            candidate = String(candidate.prefix(72)).trimmingCharacters(in: .whitespaces) + "…"
        }
        return candidate.isEmpty ? fallback : candidate
    }

    /// Update a committed `note.md` in place with its transcript.
    ///
    /// Rewrites the title in front matter *and* the leading H1 — the library
    /// derives one from the other, so changing only one of them produces a note
    /// whose name depends on which surface you are looking at.
    ///
    /// The body is replaced only when it is still the empty stub the capture
    /// wrote. Anything the user has typed since is theirs, and a transcription
    /// arriving late must never overwrite it.
    public static func applyTranscript(
        to noteURL: URL, transcript: Transcript, fallbackTitle: String
    ) throws {
        let raw = try String(contentsOf: noteURL, encoding: .utf8)
        let newTitle = title(from: transcript.text, fallback: fallbackTitle)

        var (frontMatter, body) = split(raw)
        frontMatter = setField(frontMatter, "title", "\"\(escape(newTitle))\"")
        frontMatter = setField(frontMatter, "transcribed", "true")

        let stub = bodyIsUntouchedStub(body)
        let newBody =
            stub
            ? "# \(newTitle)\n\n\(transcript.text)\n"
            : replaceLeadingH1(body, with: newTitle)

        // Blank line after the front matter, matching what the library's own
        // serializer writes — a captured note should be byte-shaped like any
        // other note, not merely parseable as one.
        try (frontMatter + "\n\n" + newBody).write(to: noteURL, atomically: true, encoding: .utf8)
    }

    /// True when the body is just the heading the capture wrote, with nothing
    /// under it — i.e. nobody has typed into this note yet.
    static func bodyIsUntouchedStub(_ body: String) -> Bool {
        let lines = body.split(separator: "\n", omittingEmptySubsequences: true)
        return lines.count <= 1 && (lines.first?.hasPrefix("# ") ?? true)
    }

    static func split(_ raw: String) -> (frontMatter: String, body: String) {
        guard raw.hasPrefix("---"), let end = raw.range(of: "\n---", range: raw.index(raw.startIndex, offsetBy: 3)..<raw.endIndex)
        else { return ("", raw) }
        let fmEnd = raw.index(end.upperBound, offsetBy: 0)
        let frontMatter = String(raw[raw.startIndex..<fmEnd])
        var body = String(raw[fmEnd...])
        while body.hasPrefix("\n") { body.removeFirst() }
        return (frontMatter, body)
    }

    /// Set a front-matter field, appending it if it wasn't there.
    static func setField(_ frontMatter: String, _ key: String, _ value: String) -> String {
        var lines = frontMatter.components(separatedBy: "\n")
        if let i = lines.firstIndex(where: { $0.hasPrefix("\(key):") }) {
            lines[i] = "\(key): \(value)"
        } else if let closing = lines.lastIndex(of: "---") {
            lines.insert("\(key): \(value)", at: closing)
        }
        return lines.joined(separator: "\n")
    }

    static func replaceLeadingH1(_ body: String, with title: String) -> String {
        var lines = body.components(separatedBy: "\n")
        if let i = lines.firstIndex(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }),
            lines[i].hasPrefix("# ")
        {
            lines[i] = "# \(title)"
            return lines.joined(separator: "\n")
        }
        return body
    }

    static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
    }
}
